import { PrismaClient } from "@prisma/client";

// TP.HCM districts and wards data
const hcmData = {
  province: {
    code: "79",
    name: "Thành phố Hồ Chí Minh",
    code_name: "thanh_pho_ho_chi_minh",
    full_name: "Thành phố Hồ Chí Minh",
    phone_code: 28,
    division_type: "tỉnh",
  },
  districts: [
    {
      code: "760",
      name: "Quận 1",
      code_name: "quan_1",
      full_name: "Quận 1",
      province_code: "79",
      wards: [
        { code: "26740", name: "Phường Bến Nghé" },
        { code: "26743", name: "Phường Bến Thành" },
        { code: "26746", name: "Phường Cầu Kho" },
        { code: "26749", name: "Phường Cầu Ông Lãnh" },
        { code: "26752", name: "Phường Cô Giang" },
        { code: "26755", name: "Phường Đa Kao" },
        { code: "26758", name: "Phường Nguyễn Cư Trinh" },
        { code: "26761", name: "Phường Nguyễn Thái Bình" },
        { code: "26764", name: "Phường Phạm Ngũ Lão" },
        { code: "26767", name: "Phường Tân Định" },
      ],
    },
    {
      code: "762",
      name: "Quận Gò Vấp",
      code_name: "quan_go_vap",
      full_name: "Quận Gò Vấp",
      province_code: "79",
      wards: [
        { code: "26890", name: "Phường 01" },
        { code: "26893", name: "Phường 03" },
        { code: "26896", name: "Phường 04" },
        { code: "26899", name: "Phường 05" },
        { code: "26902", name: "Phường 06" },
        { code: "26905", name: "Phường 07" },
        { code: "26908", name: "Phường 08" },
        { code: "26911", name: "Phường 09" },
        { code: "26914", name: "Phường 10" },
        { code: "26917", name: "Phường 11" },
        { code: "26920", name: "Phường 12" },
        { code: "26923", name: "Phường 13" },
        { code: "26926", name: "Phường 14" },
        { code: "26929", name: "Phường 15" },
        { code: "26932", name: "Phường 16" },
        { code: "26935", name: "Phường 17" },
      ],
    },
    {
      code: "763",
      name: "Quận Bình Thạnh",
      code_name: "quan_binh_thanh",
      full_name: "Quận Bình Thạnh",
      province_code: "79",
      wards: [
        { code: "26938", name: "Phường 01" },
        { code: "26941", name: "Phường 02" },
        { code: "26944", name: "Phường 03" },
        { code: "26947", name: "Phường 05" },
        { code: "26950", name: "Phường 06" },
        { code: "26953", name: "Phường 07" },
        { code: "26956", name: "Phường 11" },
        { code: "26959", name: "Phường 12" },
        { code: "26962", name: "Phường 13" },
        { code: "26965", name: "Phường 14" },
        { code: "26968", name: "Phường 15" },
        { code: "26971", name: "Phường 17" },
        { code: "26974", name: "Phường 19" },
        { code: "26977", name: "Phường 21" },
        { code: "26980", name: "Phường 22" },
      ],
    },
    {
      code: "764",
      name: "Quận Tân Bình",
      code_name: "quan_tan_binh",
      full_name: "Quận Tân Bình",
      province_code: "79",
      wards: [
        { code: "26983", name: "Phường 01" },
        { code: "26986", name: "Phường 02" },
        { code: "26989", name: "Phường 03" },
        { code: "26992", name: "Phường 04" },
        { code: "26995", name: "Phường 05" },
        { code: "26998", name: "Phường 06" },
        { code: "27001", name: "Phường 07" },
        { code: "27004", name: "Phường 08" },
        { code: "27007", name: "Phường 09" },
        { code: "27010", name: "Phường 10" },
        { code: "27013", name: "Phường 11" },
        { code: "27016", name: "Phường 12" },
        { code: "27019", name: "Phường 13" },
        { code: "27022", name: "Phường 14" },
        { code: "27025", name: "Phường 15" },
      ],
    },
    {
      code: "766",
      name: "Quận Phú Nhuận",
      code_name: "quan_phu_nhuan",
      full_name: "Quận Phú Nhuận",
      province_code: "79",
      wards: [
        { code: "27118", name: "Phường 01" },
        { code: "27121", name: "Phường 02" },
        { code: "27124", name: "Phường 03" },
        { code: "27127", name: "Phường 04" },
        { code: "27130", name: "Phường 05" },
        { code: "27133", name: "Phường 07" },
        { code: "27136", name: "Phường 08" },
        { code: "27139", name: "Phường 09" },
        { code: "27142", name: "Phường 10" },
        { code: "27145", name: "Phường 11" },
        { code: "27148", name: "Phường 13" },
        { code: "27151", name: "Phường 15" },
        { code: "27154", name: "Phường 17" },
      ],
    },
    {
      code: "780",
      name: "Huyện Bình Chánh",
      code_name: "huyen_binh_chanh",
      full_name: "Huyện Bình Chánh",
      province_code: "79",
      wards: [
        { code: "27595", name: "Thị trấn Tân Túc" },
        { code: "27598", name: "Xã Phạm Văn Hai" },
        { code: "27601", name: "Xã Vĩnh Lộc A" },
        { code: "27604", name: "Xã Vĩnh Lộc B" },
        { code: "27607", name: "Xã Bình Lợi" },
        { code: "27610", name: "Xã Lê Minh Xuân" },
        { code: "27613", name: "Xã Tân Nhựt" },
        { code: "27616", name: "Xã Tân Kiên" },
        { code: "27619", name: "Xã Bình Hưng" },
        { code: "27622", name: "Xã Phong Phú" },
        { code: "27625", name: "Xã An Phú Tây" },
        { code: "27628", name: "Xã Hưng Long" },
        { code: "27631", name: "Xã Đa Phước" },
        { code: "27634", name: "Xã Tân Quý Tây" },
        { code: "27637", name: "Xã Bình Chánh" },
        { code: "27640", name: "Xã Quy Đức" },
      ],
    },
  ],
};

export async function seedHCMAreas(prisma: PrismaClient) {
  console.log("🏢 Seeding HCM areas data...");

  // Note: This seed doesn't create actual province/district/ward records
  // as they are handled by the external API
  // This data structure is used for reference in route assignments

  console.log("✅ HCM areas data prepared for reference");
}

export { hcmData };
