import { NotificationItem } from './types';

export const mockNotifications: NotificationItem[] = [
  {
    id: 'noti1',
    type: 'policy',
    title: 'Cập nhật chính sách phân loại rác',
    summary: 'Từ 01/07/2024, quy định mới về phân loại rác tại nguồn sẽ được áp dụng.',
    content: `Chi tiết: Từ 01/07/2024, mọi hộ gia đình phải phân loại rác hữu cơ và vô cơ riêng biệt.\n\nNội dung chính sách rất dài:\n- Điều 1: Mục đích và phạm vi áp dụng\n- Điều 2: Quy định về phân loại rác tại nguồn\n- Điều 3: Trách nhiệm của hộ gia đình\n- Điều 4: Xử phạt vi phạm\n\n1. Mỗi hộ gia đình phải có 2 thùng rác riêng biệt.\n2. Rác hữu cơ gồm: thức ăn thừa, rau củ quả, ...\n3. Rác vô cơ gồm: nhựa, kim loại, thủy tinh, ...\n4. Vi phạm sẽ bị phạt từ 500.000đ đến 2.000.000đ.\n\nVui lòng đọc file đính kèm để biết chi tiết toàn bộ văn bản pháp lý (20 trang).\n\nTrân trọng,\nUBND Quận C`,
    sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    read: false,
    attachmentUrl: '/files/policy-phanloai.pdf',
  },
  {
    id: 'noti2',
    type: 'policy',
    title: 'Thông báo về mức phí thu gom mới năm 2024',
    summary: 'UBND thành phố ban hành mức phí thu gom rác mới áp dụng từ 01/08/2024.',
    content: `Quyết định 67/2025/QĐ-UBND 2025 có hiệu lực thi hành kể từ ngày 01/6/2025 và thay thế Quyết định 38/2018/QĐ-UBND 2018 và Quyết định 20/2021/QĐ-UBND của Ủy ban nhân dân Thành phố Hồ Chí Minh.\n\nTheo đó, phạm vi áp dụng Quyết định 67/2025/QĐ-UBND như sau:\n\n- Quy định này quy định về hình thức và mức giá cụ thể (mức kinh phí) cơ quan, tổ chức, cơ sở sản xuất, kinh doanh, dịch vụ, chủ đầu tư xây dựng và kinh doanh hạ tầng khu sản xuất, kinh doanh, dịch vụ tập trung, cụm công nghiệp, hộ gia đình, cá nhân phải chi trả cho công tác thu gom, vận chuyển, xử lý chất thải rắn sinh hoạt dựa trên khối lượng hoặc thể tích chất thải (chất thải rắn sinh hoạt sau đây được viết tắt là CTRSH).\n\n- Các nội dung liên quan giá cụ thể đối với dịch vụ thu gom, vận chuyển, xử lý CTRSH trên địa bàn Thành phố Hồ Chí Minh chưa được quy định tại Quy định này thì được thực hiện theo quy định hiện hành do cơ quan quản lý nhà nước có thẩm quyền ban hành.\n\nNhư vậy, từ ngày 01/6/2025, mức giá dịch vụ thu gom, vận chuyển và xử lý chất thải rắn sinh hoạt (CTRSH) tại TP.HCM được áp dụng theo Quyết định 67/2025/QĐ-UBND, phân theo từng nhóm đối tượng, khu vực và khối lượng phát sinh.`,
    sentAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    read: false,
    attachmentUrl: '/files/fee-policy-2024.pdf',
  },
  {
    id: 'noti3',
    type: 'schedule',
    title: 'Thay đổi lịch thu gom tuần này',
    summary: 'Lịch thu gom ngày thứ 5 chuyển sang thứ 6 do thời tiết xấu.',
    content: 'Do ảnh hưởng của mưa lớn, lịch thu gom ngày thứ 5 (13/06) sẽ chuyển sang thứ 6 (14/06). Mong quý dân thông cảm.',
    sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: 'noti4',
    type: 'system',
    title: 'Bảo trì hệ thống app',
    summary: 'App sẽ bảo trì từ 22h ngày 15/06 đến 2h sáng hôm sau.',
    content: 'Để nâng cấp tính năng, hệ thống sẽ bảo trì từ 22h ngày 15/06 đến 2h sáng 16/06. Trong thời gian này, một số chức năng có thể bị gián đoạn.',
    sentAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'noti5',
    type: 'environment',
    title: 'Hưởng ứng ngày môi trường thế giới',
    summary: 'Tham gia các hoạt động bảo vệ môi trường tại địa phương vào ngày 05/06.',
    content: 'UBND phường phát động phong trào làm sạch đường phố, trồng cây xanh vào ngày 05/06. Mọi người dân đều được khuyến khích tham gia.',
    sentAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'noti6',
    type: 'policy',
    title: 'Quy định mới về xử lý rác thải nguy hại',
    summary: 'Từ 01/09/2024, rác thải nguy hại phải được phân loại và xử lý riêng.',
    content: `Tại Điều 72 Luật Bảo vệ môi trường 2020 quy định về yêu cầu quản lý đối với chất thải, trong đó bao gồm chất thải nguy hiểm như sau:\n\n- Chất thải phải được quản lý trong toàn bộ quá trình phát sinh, giảm thiểu, phân loại, thu gom, lưu giữ, trung chuyển, vận chuyển, tái sử dụng, tái chế, xử lý, tiêu hủy;\n\n- Chủ nguồn thải chất thải nguy hại có trách nhiệm tái sử dụng, tái chế, xử lý và thu hồi năng lượng từ chất thải hoặc chuyển giao cho cơ sở có chức năng, giấy phép môi trường phù hợp để xử lý;\n\n- Chủ nguồn thải chất thải công nghiệp phải kiểm soát có trách nhiệm phân định chất thải là chất thải nguy hại hoặc chất thải rắn công nghiệp thông thường thông qua hoạt động lấy, phân tích mẫu do cơ sở có chức năng, đủ năng lực thực hiện theo quy định của pháp luật. Chất thải công nghiệp sau khi phân định phải được quản lý theo quy định của pháp luật;\n\n- Chất thải đáp ứng tiêu chuẩn, quy chuẩn kỹ thuật của nguyên liệu, nhiên liệu, vật liệu theo quy định của pháp luật về chất lượng sản phẩm, hàng hóa được quản lý như sản phẩm, hàng hóa và được phép sử dụng trực tiếp làm nguyên liệu, nhiên liệu, vật liệu cho hoạt động sản xuất;\n\n- Tổ chức, cá nhân vận chuyển chất thải nguy hại phải xử lý có trách nhiệm vận chuyển chất thải đến cơ sở có chức năng, giấy phép môi trường phù hợp hoặc chuyển giao cho tổ chức, cá nhân vận chuyển khác để vận chuyển đến cơ sở có chức năng, giấy phép môi trường phù hợp;\n\n`,
    sentAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    read: false,
    attachmentUrl: '/files/hazardous-policy.pdf',
  },
  {
    id: 'noti7',
    type: 'schedule',
    title: 'Thông báo nghỉ lễ Quốc khánh',
    summary: 'Lịch thu gom rác sẽ tạm ngưng vào ngày 02/09.',
    content: 'Do nghỉ lễ Quốc khánh, lịch thu gom rác sẽ tạm ngưng vào ngày 02/09 và hoạt động lại vào ngày 03/09.',
    sentAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'noti8',
    type: 'system',
    title: 'Cập nhật phiên bản app mới',
    summary: 'Phiên bản 2.0 với nhiều tính năng mới đã sẵn sàng.',
    content: 'Hãy cập nhật app lên phiên bản mới nhất để trải nghiệm các tính năng mới như: nhắc nhở thu gom, tra cứu hóa đơn, phản hồi nhanh.',
    sentAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
]; 