import type { Feedback, FeedbackStats } from './types';

export const mockFeedbacks: Feedback[] = [
  {
    id: 'fb001',
    code: 'FB202406-001',
    createdAt: '2024-06-10T08:30:00Z',
    sender: { id: 'u001', name: 'Nguyễn Văn An', role: 'citizen' },
    channel: 'auto',
    type: 'complaint',
    content: 'Rác chưa được thu đúng giờ tại khu vực nhà tôi.',
    relatedScheduleId: 'SCH1001',
    status: 'pending',
    priority: 'urgent',
    attachments: [
      { id: 'att1', url: '/uploads/feedback/fb001_img1.jpg', type: 'image', name: 'Ảnh hiện trường' },
    ],
  },
  {
    id: 'fb002',
    code: 'FB202406-002',
    createdAt: '2024-06-09T14:15:00Z',
    sender: { id: 'u002', name: 'Trần Thị Bích Ngọc', role: 'citizen' },
    channel: 'manual',
    type: 'suggestion',
    content: 'Nên bổ sung thêm thùng rác phân loại tại khu vực công viên.',
    status: 'in_progress',
    priority: 'normal',
    attachments: [],
    handler: { id: 'admin1', name: 'Admin Nguyễn' },
    notes: 'Đã chuyển cho phòng môi trường.',
  },
  {
    id: 'fb003',
    code: 'FB202406-003',
    createdAt: '2024-06-08T10:00:00Z',
    sender: { id: 'c001', name: 'Lê Minh Quân', role: 'collector' },
    channel: 'auto',
    type: 'proposal',
    content: 'Đề xuất thay đổi tuyến thu gom để giảm ùn tắc giao thông.',
    status: 'resolved',
    priority: 'normal',
    attachments: [],
    handler: { id: 'admin2', name: 'Admin Trần' },
    handledAt: '2024-06-09T09:00:00Z',
    notes: 'Đã cập nhật tuyến mới.',
  },
  {
    id: 'fb004',
    code: 'FB202406-004',
    createdAt: '2024-06-07T16:45:00Z',
    sender: { id: 'u003', name: 'Phạm Minh Dương', role: 'citizen' },
    channel: 'manual',
    type: 'complaint',
    content: 'Nhân viên thu gom không thu hết rác trước nhà.',
    status: 'in_progress',
    priority: 'urgent',
    attachments: [
      { id: 'att2', url: '/uploads/feedback/fb004_img1.jpg', type: 'image', name: 'Ảnh rác còn sót' },
    ],
    handler: { id: 'admin1', name: 'Admin Nguyễn' },
  },
  {
    id: 'fb005',
    code: 'FB202406-005',
    createdAt: '2024-06-06T11:20:00Z',
    sender: { id: 'c002', name: 'Ngô Thị Hồng Nhung', role: 'collector' },
    channel: 'auto',
    type: 'suggestion',
    content: 'Nên trang bị thêm găng tay cho nhân viên.',
    status: 'pending',
    priority: 'normal',
    attachments: [],
  },
  {
    id: 'fb006',
    code: 'FB202406-006',
    createdAt: '2024-06-05T09:10:00Z',
    sender: { id: 'u004', name: 'Vũ Thị Phương Anh', role: 'citizen' },
    channel: 'manual',
    type: 'proposal',
    content: 'Đề xuất tổ chức chương trình tuyên truyền phân loại rác.',
    status: 'resolved',
    priority: 'normal',
    attachments: [],
    handler: { id: 'admin3', name: 'Admin Lê' },
    handledAt: '2024-06-06T15:00:00Z',
    notes: 'Đã lên kế hoạch tổ chức tháng 7.',
  },
  {
    id: 'fb007',
    code: 'FB202406-007',
    createdAt: '2024-06-04T13:30:00Z',
    sender: { id: 'u005', name: 'Đặng Văn Giang', role: 'citizen' },
    channel: 'auto',
    type: 'complaint',
    content: 'Xe thu gom gây tiếng ồn lớn vào ban đêm.',
    status: 'pending',
    priority: 'urgent',
    attachments: [],
  },
  {
    id: 'fb008',
    code: 'FB202406-008',
    createdAt: '2024-06-03T17:00:00Z',
    sender: { id: 'c003', name: 'Phan Văn Hùng', role: 'collector' },
    channel: 'manual',
    type: 'suggestion',
    content: 'Đề nghị tăng lương cho nhân viên thu gom làm ca đêm.',
    status: 'in_progress',
    priority: 'normal',
    attachments: [],
    handler: { id: 'admin2', name: 'Admin Trần' },
  },
];

export const mockFeedbackStats: FeedbackStats = {
  total: 8,
  resolved: 4,
  byType: {
    complaint: 3,
    suggestion: 3,
    proposal: 2,
  },
  urgent: 3,
  month: '2024-06',
};
